# see https://s.apache.org/asfyaml
github:
  description: "Apache Maven Build Cache Extension"
  homepage: https://maven.apache.org/ref/caching
  labels:
    - java
    - build-management
    - apache-maven
    - maven
